<?php
return array(
    //Videos
    'rv' => 'video/vnd.rn-realvideo',
    '3gp' => 'video/3gpp',
    'ts' => 'video/MP2T',
    'avi' => 'video/x-msvideo',
    'flv' => 'video/x-flv',
    'mov' => 'video/quicktime',
    'movie' => 'video/x-sgi-movie',
    'mp4' => 'video/mp4',
    'm4v' => 'video/x-m4v',
    'mpe' => 'video/mpeg',
    'mpeg' => 'video/mpeg',
    'mpg' => 'video/mpeg',
    'mts' => array('video/vnd.mts', 'model/vnd.mts'),
    'qt' => 'video/quicktime',
    'wmv' => 'video/x-ms-wmv',
    'mkv' => 'video/x-matroska',
    'webm' => 'video/webm',
    'swf' => array('video/swf', 'application/x-shockwave-flash'),

    // Audio
    'aif' => 'audio/x-aiff',
    'aifc' => 'audio/x-aiff',
    'aiff' => 'audio/x-aiff',
    'mid' => 'audio/midi',
    'midi' => 'audio/midi',
    'mp2' => 'audio/mpeg',
    'mp3' => array('audio/mp3', 'audio/mpg', 'audio/mpeg3', 'audio/mpeg'),
    'mpga' => 'audio/mpeg',
    'ra' => 'audio/x-realaudio',
    'ram' => 'audio/x-pn-realaudio',
    'rm' => 'audio/x-pn-realaudio',
    'rpm' => 'audio/x-pn-realaudio-plugin',
    'wav' => 'audio/x-wav',
    'm4a' => 'audio/mp4',

    // Images
    'bmp' => 'image/bmp',
    'gif' => 'image/gif',
    'jpe' => array('image/jpeg', 'image/pjpeg'),
    'jpeg' => array('image/jpeg', 'image/pjpeg'),
    'jpg' => array('image/jpeg', 'image/pjpeg'),
    'png' => 'image/png',
    'tif' => 'image/tiff',
    'tiff' => 'image/tiff',

    // Docs
    'ai' => 'application/postscript',
    'class' => 'application/octet-stream',
    'css' => 'text/css',
    'csv' => array('text/x-comma-separated-values', 'text/comma-separated-values', 'application/octet-stream'),
    'dcr' => 'application/x-director',
    'dir' => 'application/x-director',
    'dll' => 'application/octet-stream',
    'dms' => 'application/octet-stream',
    'doc' => 'application/msword',
    'docx' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'dvi' => 'application/x-dvi',
    'dxr' => 'application/x-director',
    'eps' => 'application/postscript',
    'htm' => 'text/html',
    'html' => 'text/html',
    'js' => 'application/x-javascript',
    'json' => array('application/json', 'text/json'),
    'pdf' => array('application/pdf', 'application/x-download'),
    'php' => array('application/x-httpd-php', 'text/x-php'),
    'ppt' => array('application/powerpoint', 'application/vnd.ms-powerpoint'),
    'psd' => 'application/x-photoshop',
    'rtf' => 'text/rtf',
    'rtx' => 'text/richtext',
    'shtml' => 'text/html',
    'text' => 'text/plain',
    'tgz' => array('application/x-tar', 'application/x-gzip-compressed'),
    'txt' => 'text/plain',
    'wbxml' => 'application/wbxml',
    'wmlc' => 'application/wmlc',
    'word' => array('application/msword', 'application/octet-stream'),
    'xht' => 'application/xhtml+xml',
    'xhtml' => 'application/xhtml+xml',
    'xl' => 'application/excel',
    'xls' => array('application/excel', 'application/vnd.ms-excel', 'application/msexcel'),
    'xlsx' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'xml' => 'text/xml',
    'xsl' => 'text/xml'
);